### ISSUE TITLE
Segmentation fault on aarch64 when PAGE_SIZE is 64KB

### ISSUE THREAD

**Issue by ginomcevoy** [Snaipe/Criterion#289]
Criterion from bleeding/master branches fails with segmentation fault when running a simple example on aarch64 architecture.

Code example (from the docs):

```
#include <criterion/criterion.h>

int main(int argc, char *argv[]) {
    struct criterion_test_set *tests = criterion_initialize();

    int result = 0;
    if (criterion_handle_args(argc, argv, true))
        result = !criterion_run_all_tests(tests);

    criterion_finalize(tests);
    return result;
}
```

Here is the gdb backtrace:

```
#0  0x0000ffffbe5362f8 in strcmp () from /lib64/libc.so.6
#1  0x0000ffffbe66256c in get_section_data (mod=<synthetic pointer>, mod=<synthetic pointer>,
    sect=<synthetic pointer>, base=0x0, name=0xffffbe745760 "cr_sts")
    at /factory/Criterion/Criterion-bleeding/src/compat/section-elf.c:205
#2  section_getaddr (info=<optimized out>, size=<optimized out>, data=0xfffffffff198)
    at /factory/Criterion/Criterion-bleeding/src/compat/section-elf.c:240
#3  0x0000ffffbe5ccd0c in dl_iterate_phdr () from /lib64/libc.so.6
#4  0x0000ffffbe6626ac in cri_sections_getaddr (sectname=sectname@entry=0xffffbe745760 "cr_sts",
    out=out@entry=0xfffffffff200) at /factory/Criterion/Criterion-bleeding/src/compat/section-elf.c:270
#5  0x0000ffffbe65d748 in criterion_init () at /factory/Criterion/Criterion-bleeding/src/core/runner.c:128
#6  0x0000ffffbe65da68 in criterion_initialize () at /factory/Criterion/Criterion-bleeding/src/core/runner.c:232
#7  0x0000000000400964 in main (argc=1, argv=0xfffffffff448) at example_criterion.c:4
```

The problem is in src/compt/section-elf.c, it assumes a fixed page size of 4KB (it is variable in aarch64, fails when set to 64KB). Instead of '0xfff000', the code needs to calculate the page size and use (PAGE_SIZE - 1).

**Comment by Snaipe** [comment]
Thanks for reporting this issue. I have a fix to address this.

I've had a quick glance through the code to make sure that I wasn't using hardcoded constants for the page size. This seems to be the only case, but if there are others I've missed, we can reopen this issue later.
